class AIService:
    """Service for generating documents using Google Gemini."""

    def __init__(self):
        settings = get_settings()
        if settings.gemini_api_key:
            genai.configure(api_key=settings.gemini_api_key)
            self.model = genai.GenerativeModel("gemini-pro")
        else:
            self.model = None

    async def generate_document(
        self,
        document_type: DocumentType,
        user_input: str,
        additional_context: str | None = None,
    ) -> str:
        """Generate a professional document using AI.

        Returns the generated HTML content.
        """
        if not self.model:
            # Return a demo document if no API key is configured
            return self._generate_demo_document(document_type, user_input)

        prompt_template = PROMPTS.get(document_type, PROMPTS[DocumentType.REPORT])
        prompt = prompt_template.format(
            user_input=user_input,
            additional_context=additional_context or "No additional context provided.",
        )

        response = await self.model.generate_content_async(
            prompt,
            generation_config=genai.types.GenerationConfig(
                temperature=0.7,
                max_output_tokens=8000,
            ),
        )

        html_content = response.text.strip()

        # Clean up any markdown code fences the model might have added
        if html_content.startswith("```html"):
            html_content = html_content[7:]
        if html_content.startswith("```"):
            html_content = html_content[3:]
        if html_content.endswith("```"):
            html_content = html_content[:-3]

        # Wrap with professional CSS
        full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {DOCUMENT_CSS}
</head>
<body>
{html_content.strip()}
</body>
</html>"""

        return full_html

    def _generate_demo_document(
        self, document_type: DocumentType, user_input: str
    ) -> str:
        """Generate a demo document when no API key is set (for testing)."""
        title = document_type.value.title()
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {DOCUMENT_CSS}
</head>
<body>
    <div class="cover-page">
        <h1>{title}</h1>
        <p><em>Generated by DocGen AI</em></p>
    </div>
    
    <h2>Demo Document</h2>
    <p>This is a demo document generated without an AI API key. 
    To generate real professional documents, add your Google Gemini API key to the <code>.env</code> file.</p>
    
    <h2>Your Input</h2>
    <p>{user_input}</p>
    
    <h2>How It Works</h2>
    <ol>
        <li>Add your free Gemini API key to <code>.env</code></li>
        <li>Restart the server</li>
        <li>The AI will generate a full professional {title.lower()} based on your input</li>
    </ol>
    
    <div class="disclaimer">
        <strong>Demo Mode:</strong> Get your free Gemini API key at 
        <a href="https://aistudio.google.com/apikey">aistudio.google.com/apikey</a>
    </div>
</body>
</html>"""


# Singleton instance
ai_service = AIService()

